---@module "competitest.git.config"
---Git integration configuration: default options, schema and option merging.
---Everything here is namespaced under the `git` key of the main CompetiTest config.

---A single problem, as reconstructed for the Git UI and passed to formatters.
---@class (exact) competitest.git.Problem
---@field platform string short platform code, e.g. `"cf"`, `"at"`, `"lc"`, `"cc"`, `"cs"`
---@field contest string contest identifier, e.g. `"2050"`, `"ABC412"` (may be empty)
---@field index string problem index within the contest, e.g. `"A"`, `"C"` (may be empty)
---@field id string full problem identifier, e.g. `"CF2050A"`, `"ABC412C"`, `"LC42"`, `"CSES1638"`
---@field title string human-readable problem title (may be empty when unknown)
---@field url string problem URL (may be empty when unknown)
---@field filepath string absolute path to the source file

---Metadata gathered from the Git UI and passed to formatters.
---@class (exact) competitest.git.Meta
---@field type string commit type, e.g. `"practice"`, `"solve"`
---@field difficulty string chosen difficulty, e.g. `"1700"`, `"Hard"`
---@field language string inferred/overridden language label, e.g. `"cpp23"`, `"python"`
---@field attempts integer number of attempts (defaults to 1)
---@field editorial boolean whether the solution follows an editorial
---@field contest boolean whether the problem was solved in contest mode

---Platform detection and identifier construction entry.
---@class (exact) competitest.git.Platform
---@field code string short platform code used in commit messages
---@field match fun(url: string, group: string): boolean predicate deciding whether an entry matches a task
---@field id fun(ctx: competitest.git.PlatformContext): competitest.git.PlatformResult build id/contest/index from task data

---Context handed to a platform `id` builder.
---@class (exact) competitest.git.PlatformContext
---@field url string problem URL
---@field group string task group (judge + contest)
---@field name string problem name/title
---@field taskname string short identifier derived from the URL (see `receive.lua`)

---Result returned by a platform `id` builder.
---@class (exact) competitest.git.PlatformResult
---@field id string full identifier
---@field contest string? contest identifier
---@field index string? problem index

---Selection-mode key mappings.
---@class (exact) competitest.git.mappings.selection
---@field commit keymaps enter Commit Mode
---@field push keymaps push to remote
---@field stage keymaps stage current file
---@field unstage keymaps unstage current file
---@field refresh keymaps refresh git state
---@field close keymaps close the UI

---Commit-mode key mappings.
---@class (exact) competitest.git.mappings.commit
---@field confirm keymaps confirm and commit
---@field back keymaps return to Selection Mode
---@field next_field keymaps focus next field
---@field prev_field keymaps focus previous field
---@field edit keymaps edit the focused field (opens a dropdown or prompt)
---@field cycle_next keymaps cycle the focused field to its next value
---@field cycle_prev keymaps cycle the focused field to its previous value

---Git integration configuration.
---@class (exact) competitest.Config.git
---@field enabled boolean master switch; when `false` no command is registered and no hook runs
---@field commit_on_accept false | "ui" | "auto" what to do when all testcases pass: `false` nothing, `"ui"` open the commit UI, `"auto"` commit directly
---@field default_type string default commit type selected in the UI
---@field types string[] available commit types
---@field commit_formatter nil | fun(problem: competitest.git.Problem, meta: competitest.git.Meta): string custom commit message formatter
---@field body_formatter nil | fun(problem: competitest.git.Problem, meta: competitest.git.Meta): string custom commit body formatter
---@field body boolean include a commit body generated by `body_formatter`
---@field push_after_commit boolean automatically push after a successful commit
---@field stage_testcases boolean also stage the problem's testcase files when staging the solution
---@field meta_directory string directory holding sidecars, relative to source file; supports `@/` (see `testcases_directory`)
---@field meta_file_format string sidecar file name, with CompetiTest file-format modifiers
---@field language_map table<string, string> override filetype/extension to language label mapping
---@field difficulty table<string, string[]> per-platform difficulty lists, keyed by platform code
---@field platforms competitest.git.Platform[] ordered platform detection table
---@field width number ratio between UI width and Neovim width (between 0 and 1)
---@field height number maximum ratio between UI height and Neovim height (between 0 and 1); the window shrinks to fit its content
---@field mappings { selection: competitest.git.mappings.selection, commit: competitest.git.mappings.commit }

local M = {}

---Build a range of numeric strings from `start` to `stop` (inclusive) with the given `step`.
---@param start integer
---@param stop integer
---@param step integer
---@return string[]
local function num_range(start, stop, step)
	local list = {}
	for n = start, stop, step do
		table.insert(list, tostring(n))
	end
	return list
end

---Default git integration configuration.
---@type competitest.Config.git
M.defaults = {
	enabled = false,
	commit_on_accept = false,
	default_type = "practice",
	types = { "solve", "practice", "upsolve", "virtual", "refactor", "optimize", "editorial", "template" },
	commit_formatter = nil,
	body_formatter = nil,
	body = false,
	push_after_commit = false,
	stage_testcases = false,
	meta_directory = ".",
	meta_file_format = "$(FNOEXT).cpmeta.json",
	language_map = {},
	difficulty = {
		cf = num_range(800, 3500, 100),
		at = num_range(400, 3600, 200),
		lc = { "Easy", "Medium", "Hard" },
		cc = { "1★", "2★", "3★", "4★", "5★", "6★", "7★" },
		cs = { "Introductory", "Sorting", "Data Structures", "Dynamic Programming", "Graph", "Range Queries", "Tree", "Math", "String", "Geometry", "Advanced" },
	},
	platforms = {
		{
			code = "cf",
			match = function(url, group)
				return string.find(url, "codeforces.com", 1, true) ~= nil or string.find(group or "", "Codeforces", 1, true) ~= nil
			end,
			---@param ctx competitest.git.PlatformContext
			id = function(ctx)
				local contest, index = string.match(ctx.url, "/(%d+)/problem/(%u+%d*)")
				if not contest then
					contest, index = string.match(ctx.url, "/problemset/problem/(%d+)/(%u+%d*)")
				end
				if not contest then
					contest, index = string.match(ctx.url, "/gym/(%d+)/problem/(%u+%d*)")
				end
				if contest and index then
					return { id = "CF" .. contest .. index, contest = contest, index = index }
				end
				return { id = "CF" .. ctx.taskname }
			end,
		},
		{
			code = "at",
			match = function(url, group)
				return string.find(url, "atcoder.jp", 1, true) ~= nil or string.find(group or "", "AtCoder", 1, true) ~= nil
			end,
			---@param ctx competitest.git.PlatformContext
			id = function(ctx)
				local slug = string.match(ctx.url, "/tasks/([%w_]+)") or ctx.taskname
				-- e.g. "abc412_c" -> contest "ABC412", index "C"
				local contest, index = string.match(slug, "^(%a+%d+)_(%w+)$")
				if contest and index then
					return { id = (contest .. index):upper(), contest = contest:upper(), index = index:upper() }
				end
				return { id = slug:upper() }
			end,
		},
		{
			code = "lc",
			match = function(url, group)
				return string.find(url, "leetcode.com", 1, true) ~= nil or string.find(group or "", "LeetCode", 1, true) ~= nil
			end,
			---@param ctx competitest.git.PlatformContext
			id = function(ctx)
				-- LeetCode names are usually "42. Trapping Rain Water"
				local number = string.match(ctx.name, "^(%d+)%.")
				if number then
					return { id = "LC" .. number, index = number }
				end
				local slug = string.match(ctx.url, "/problems/([%w-]+)") or ctx.taskname
				return { id = "LC-" .. slug }
			end,
		},
		{
			code = "cc",
			match = function(url, group)
				return string.find(url, "codechef.com", 1, true) ~= nil or string.find(group or "", "CodeChef", 1, true) ~= nil
			end,
			---@param ctx competitest.git.PlatformContext
			id = function(ctx)
				local code = string.match(ctx.url, "/problems/([%w_]+)") or ctx.taskname
				return { id = "CC" .. code }
			end,
		},
		{
			code = "cs",
			match = function(url, group)
				return string.find(url, "cses.fi", 1, true) ~= nil or string.find(group or "", "CSES", 1, true) ~= nil
			end,
			---@param ctx competitest.git.PlatformContext
			id = function(ctx)
				local number = string.match(ctx.url, "/task/(%d+)") or ctx.taskname
				return { id = "CSES" .. number, contest = number }
			end,
		},
	},
	width = 0.6,
	height = 0.6,
	mappings = {
		selection = {
			commit = "c",
			push = "P",
			stage = "a",
			unstage = "u",
			refresh = "r",
			close = { "q", "<esc>" },
		},
		commit = {
			confirm = "<cr>",
			back = "<esc>",
			next_field = { "<tab>", "j", "<down>" },
			prev_field = { "<s-tab>", "k", "<up>" },
			edit = { "<space>", "e" },
			cycle_next = { "<right>", "l" },
			cycle_prev = { "<left>", "h" },
		},
	},
}

---Keys whose list values must be replaced (not index-merged) when the user overrides them.
---`vim.tbl_deep_extend` merges array-like tables by key, which corrupts ordered lists;
---these are assigned verbatim from the user options instead.
---@param merged competitest.Config.git the deep-merged git config (mutated in place)
---@param user competitest.Config.git? the user-provided git options
function M.fix_list_options(merged, user)
	if not user then
		return
	end
	if user.types then
		merged.types = user.types
	end
	if user.platforms then
		merged.platforms = user.platforms
	end
	if user.difficulty then
		for platform, list in pairs(user.difficulty) do
			merged.difficulty[platform] = list
		end
	end
end

return M
